name: ictrl
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  connectivity_plus: ^6.1.4
  http: ^1.4.0
  mailer: ^6.4.1
  device_info_plus: ^11.5.0
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1
  installed_apps: ^1.6.0
  permission_handler: ^12.0.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  crypto: ^3.0.6
  firebase_storage: ^12.4.10
  external_app_launcher: ^4.0.3
  flutter_local_notifications: ^19.3.1
  flutter_foreground_task: ^9.1.0
  workmanager: ^0.7.0
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/ictrllogo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ictrldemo.png"